-- ========================================
-- SCHEMA DATABASE SCUOLA
-- File: schema_database.sql
-- Descrizione: Creazione di tutte le tabelle
-- ========================================

-- 1. Tabella AULE
CREATE OR REPLACE TABLE AULE (
    NOME VARCHAR(50) PRIMARY KEY,
    CAPIENZA INT NOT NULL
);

-- 2. Tabella CLASSI
CREATE OR REPLACE TABLE CLASSI (
    ID_C INT PRIMARY KEY AUTO_INCREMENT,
    SEZIONE VARCHAR(5),
    ANNO INT,
    N_STUDENTI INT
);

-- 3. Tabella DOCENTI
CREATE OR REPLACE TABLE DOCENTI (
    ID_D INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    COGNOME VARCHAR(50),
    MATERIA VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    PWD VARCHAR(255)
);

-- 4. Tabella AMMINISTRATORI
CREATE OR REPLACE TABLE AMMINISTRATORI (
    ID_A INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    COGNOME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    PWD VARCHAR(255)
);

-- 5. Tabella STUDENTI
CREATE OR REPLACE TABLE STUDENTI (
    ID_S INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    COGNOME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    PWD VARCHAR(255),
    ID_C INT,
    FOREIGN KEY (ID_C) REFERENCES CLASSI(ID_C)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- 6. Tabella ORARIO
CREATE OR REPLACE TABLE ORARIO (
    ID_ORARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_D INT,
    ID_C INT,
    NOME_AULA VARCHAR(50),
    GIORNO VARCHAR(20),
    ORA_INI TIME,
    ORA_FIN TIME,
    FOREIGN KEY (ID_D) REFERENCES DOCENTI(ID_D)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_C) REFERENCES CLASSI(ID_C)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (NOME_AULA) REFERENCES AULE(NOME)
    ON DELETE CASCADE ON UPDATE CASCADE
);