-- 1. Tabella AULE (Indipendente)
CREATE TABLE AULE (
    NOME VARCHAR(50) PRIMARY KEY,
    CAPIENZA INT NOT NULL
);

-- 2. Tabella DOCENTI (Indipendente)
CREATE TABLE DOCENTI (
    ID_D INT PRIMARY KEY,
    NOME VARCHAR(50),
    COGNOME VARCHAR(50),
    MATERIA VARCHAR(50),
    PWD VARCHAR(255) -- Password
);

-- 3. Tabella AMMINISTRATORI (Indipendente)
CREATE TABLE AMMINISTRATORI (
    ID_A INT PRIMARY KEY,
    NOME VARCHAR(50),
    COGNOME VARCHAR(50),
    PWD VARCHAR(255)
);

-- 4. Tabella CLASSI (Indipendente dal punto di vista gerarchico)
CREATE TABLE CLASSI (
    ID_C INT PRIMARY KEY,
    SEZIONE VARCHAR(5),
    ANNO INT,
    N_STUDENTI INT
);

-- 5. Tabella STUDENTI (Dipende da CLASSI tramite ID_C)
CREATE TABLE STUDENTI (
    ID_S INT PRIMARY KEY,
    NOME VARCHAR(50),
    COGNOME VARCHAR(50),
    PWD VARCHAR(255),
    ID_C INT,
    FOREIGN KEY (ID_C) REFERENCES CLASSI(ID_C)
);

-- 6. Tabella ORARIO (Tabella di collegamento con chiavi esterne)
CREATE TABLE ORARIO (
    ID_ORARIO INT PRIMARY KEY,
    ID_D INT,
    ID_C INT,
    NOME_AULA VARCHAR(50),
    GIORNO VARCHAR(20),
    ORA_INI TIME,
    ORA_FIN TIME,
    FOREIGN KEY (ID_D) REFERENCES DOCENTI(ID_D),
    FOREIGN KEY (ID_C) REFERENCES CLASSI(ID_C),
    FOREIGN KEY (NOME_AULA) REFERENCES AULE(NOME)
);